### ISSUE TITLE
the url of the avatar of the authors appear to me no

### ISSUE THREAD

**Issue by Nelkit** [voceconnect/thermal-api#114]
![captura de pantalla 2014-12-29 a las 18 15 53](https://cloud.githubusercontent.com/assets/4155683/5574522/e55403f8-8f86-11e4-9ad9-5f8c339f423d.png)

**Comment by csloisel** [comment]
Is there any more context you can provide on this? Is there possibly an avatar plugin being used and could you know the url that should be returning? At the moment I am unable to replicate this issue.

**Comment by Nelkit** [comment]
I solved it using get_avatar ($ user-> ID, 512); , Thank you for your help
