### ISSUE TITLE
144 posts but only 4 posts got in the JSON

### ISSUE THREAD

**Issue by clairemi** [voceconnect/thermal-api#118]
I installed the plugin in my wordpress in localhost. I use it to get all the posts in json with http://localhost:8888/wp_api/v1/posts?post_type=post, and everything works correctly. I get my 8 test posts.

The next step was to install the plugin in production : http://mydomainname.com/wp_api/v1/posts?post_type=post

The plugin is installed, but it doesn't work correctly.
I have 144 posts, I get only 4 posts in the JSON : 
{
    "found":144,
        "posts": [
            {},
            {},
            {}
        ]
}

I doesn't understand why. Is there a limit ?

**Comment by jeffstieler** [comment]
The `per_page` argument in Thermal gets mapped to `WP_Query`'s `posts_per_page`.  If that's left undefined, WordPress will grab the `posts_per_page` option and use that.  This setting can be found under Settings > Reading, labeled as "Blog pages show at most".

Hope this helps!
