### ISSUE TITLE
404 when using thermal in its own directory

### ISSUE THREAD

**Issue by iamjonas** [voceconnect/thermal-api#119]
When using wp as a submodule in git I have wordpress in its own directory resulting in a 404 when requesting posts

**Comment by jeffstieler** [comment]
Can you provide more info to help us debug this?  Thanks!

**Comment by iamjonas** [comment]
Sure.

Im not getting any error message when using wp_debug, so far so good - I think.
Using .htaccess, tried both normal links and pretty links.

both 
```
/wordpress/wp_api/v1/posts
/wp_api/v1/posts
```
returns a 404

Also tried to change the API_BASE without success.

My structure

index.php 
wp-content 
wordpress 
wp-config.php

 This is where I think the problem occurs (wp-config.php)
```php
define('WP_SITEURL', 'http://' . $_SERVER['SERVER_NAME'] . '/wordpress');
define('WP_HOME',    'http://' . $_SERVER['SERVER_NAME']);

/** wp-content directory **/
define('WP_CONTENT_DIR', $_SERVER['DOCUMENT_ROOT'] . '/wp-content');
define('WP_CONTENT_URL', 'http://' . $_SERVER['SERVER_NAME'] . '/wp-content');
```

**Comment by iamjonas** [comment]
Got it to work with a fresh install and a new wp-config.php

```php
define('WP_SITEURL', 'http://' . $_SERVER['SERVER_NAME'] . '/wordpress');
define('WP_HOME', 'http://' . $_SERVER['SERVER_NAME']);

/** Custom wp-content folder */
define('WP_CONTENT_DIR', $_SERVER['DOCUMENT_ROOT'] . '/wp-content');
define('WP_CONTENT_URL', 'http://' . $_SERVER['SERVER_NAME'] . '/wp-content');

/** Custom plugins folder */
define('WP_PLUGIN_DIR', $_SERVER['DOCUMENT_ROOT'] . '/addons');
define('WP_PLUGIN_URL', 'http://' . $_SERVER['SERVER_NAME'] . '/addons');
```

also had to register_theme_directory within the addons folder, got it to work in that manner.
